name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - demo2
  pull_request:
    branches:
      - main
      - demo2
  workflow_dispatch:

jobs:
  print_working_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: echo $PWD

  section_07_test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: Create venv
        run: |
          python -m venv deploying-machine-learning-models/venv
          source deploying-machine-learning-models/venv/bin/activate
          pip install --upgrade pip

      - name: Create venv
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip

      - name: Install tox
        run: pip install --user tox

      - name: Running app tests
        run: tox

  deploy_to_railway:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        
